package com.mifitness.miclient.crypto

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Verifies byte-for-byte parity between the Kotlin crypto implementation and
 * the Go reference (github.com/ilyasaftr/mi-fitness/internal/crypto). Test
 * vectors were generated by running the Go code with known inputs.
 */
@OptIn(ExperimentalEncodingApi::class)
class CryptoParityTest {

    // --- Test vectors from Go (known inputs → known outputs) ---

    private val ssecurity = Base64.encode("test-ssecurity-16b".encodeToByteArray())
    private val nonce = Base64.encode("12bytesnonce".encodeToByteArray())
    private val expectedSignedNonce = "1pBrTAq6mHpeOnEOvny8EWXI5Qdep3FZlr5fllYk5K0="
    private val expectedRc4 = "/qsdcUhDyVUee+M="
    private val expectedSha1 = "SYg7NOWg9IIk3WIw9HHp3Bvb6vU="
    private val expectedSha256 = "nf5vFdGrc6+Jhzk5T9Iv1yoD2wGDRYLyS7Lhxmx6rq4="
    private val expectedMd5Hex = "5F4DCC3B5AA765D61D8327DEB882CF99"

    @Test
    fun signedNonceMatchesGoOutput() {
        val result = MiCloudSigner.computeSignedNonce(ssecurity, nonce)
        assertEquals(expectedSignedNonce, result)
    }

    @Test
    fun rc4EncryptWithSkipMatchesGoOutput() {
        val key = Base64.decode(expectedSignedNonce)
        val encrypted = SkippedRC4(key).process("hello world".encodeToByteArray())
        assertEquals(expectedRc4, Base64.encode(encrypted))
    }

    @Test
    fun sha1MatchesGoOutput() {
        val hash = Hash.sha1("test input".encodeToByteArray())
        assertEquals(expectedSha1, Base64.encode(hash))
    }

    @Test
    fun sha256MatchesGoOutput() {
        val hash = Hash.sha256("test input".encodeToByteArray())
        assertEquals(expectedSha256, Base64.encode(hash))
    }

    @Test
    fun md5HexMatchesGoOutput() {
        val result = MiCloudSigner.hashPassword("password")
        assertEquals(expectedMd5Hex, result)
    }

    @Test
    fun encryptThenDecryptIsIdentity() {
        val plaintext = """{"key":"heart_rate","limit":50}"""
        val request = MiCloudSigner.buildEncryptedRequest(
            path = "/app/v1/data/get_latest_fitness_data",
            ssecurity = ssecurity,
            plaintext = plaintext,
        )
        // Decrypt the data field — should recover the original plaintext.
        val decrypted = MiCloudSigner.decryptResponse(request.signedNonce, request.data)
        assertEquals(plaintext, decrypted.decodeToString())
    }

    @Test
    fun nonceIs12BytesBase64() {
        val nonce = MiCloudSigner.generateNonce()
        val decoded = Base64.decode(nonce)
        assertEquals(12, decoded.size, "Nonce must be 12 bytes (8 random + 4 time)")
    }
}
